[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aiwolf_nlp_common"
version = "0.0.1"
license = {file = "LICENSE"}
description = "A sample python code of an AIWolf Contest's agent for Natural Language Division."
requires-python = ">=3.8"
readme = ".github/README.md"
dependencies = [
  "pycparser >= 2.22 ",
  "cffi >= 1.4.1",
  "bcrypt >= 3.2",
  "cryptography >= 3.3",
  "PyNaCl >= 1.5",
  "paramiko >= 3.5",
  "requests",
]
authors = [
  {name = "aiwolfdial", email = "aiwolf@kanolab.net"},
  {name = "nwatanabe", email = "aiwolf@kanolab.net"},
]
maintainers = [
  {name = "aiwolfdial", email = "aiwolf@kanolab.net"},
  {name = "nwatanabe", email = "aiwolf@kanolab.net"}
]
keywords = ["aiwolf", "aiwolfNLP", "aiwolfdial"]

[project.urls]
Homepage = "https://aiwolf.org"